### ISSUE TITLE
start.onnx模型在哪？

### ISSUE THREAD

**Issue by mjkld12345** [myBoris/wzry_ai#2]
大佬求问

**Comment by myBoris** [comment]
qq群文件里




布里
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "myBoris/wzry_ai"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月6日(星期六) 晚上10:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[myBoris/wzry_ai] start.onnx模型在哪？ (Issue #2)





 
大佬求问
